model:
  name: 'osnet_x1_0'
  pretrained: True
  load_weights: '/mnt/data/code/reidlog/test/cuhk03/2022-03-10-17-20-33model/model.pth.tar-226'

#cuhk03:
#  use_metric_cuhk03: True

data:
  type: 'image'
  sources: ['MLR_CUHK03']
  targets: ['MLR_CUHK03']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip', 'random_erase']
  save_dir: '/mnt/data/code/reidlog/test/cuhk03'


cuhk03:
  use_metric_cuhk03: True

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 250
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'
  save_best_only: False

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: True
  eval_freq: 1
  rerank: False
  start_eval: 200
  evaluate: True