model:
  name: 'osnet_x1_0'
#  name: 'resnet50'
#  name: 'osnet_ain_x1_0'
  pretrained: True
#  load_weights: '/mnt/data/code/reidlog/MTA-reid/osnet_ain_x1_0/2022-03-08-15-03-53model/model.pth.tar-87'
#  load_weights: '/mnt/data/code/reidlog/MTA-reid/2022-02-24-20-05-16model/model.pth.tar-59'
  load_weights: '/mnt/data/code/deep-person-reid-master/logcd/crossdomain/2021-12-15-11-51-35model/model.pth.tar-87'

#  load_weights: '/mnt/data/code/reidlog/MTA-reid/2022-02-24-22-36-02model/model-best.pth.tar'
#  load_weights: '/mnt/data/code/reidlog/mlr_market1501_hr_dsx2/hr_dsx2/2022-02-22-16-06-58model/model.pth.tar-250'
#  load_weights: '/mnt/data/code/reidlog/market1501x5/osnet_x1_0_x5_2500_E_x5_market1501_softmax_cosinelr/2022-02-24-02-07-22model/model-best.pth.tar'
#  load_weights: '/mnt/data/code/deep-person-reid-master/testlog/2022-01-18-14-57-33model/model-best.pth.tar'
#cuhk03:
#  use_metric_cuhk03: True

data:
  type: 'image'
  sources: ['MTA-reid']
  targets: ['MTA-reid']
  height: 256
  width: 128
  combineall: False
  transforms: []
  root: '/mnt/data/datasets/MTA_reid'
  save_dir: '/mnt/data/code/reidlog/MTA_reid/'
#  save_dir: '/mnt/data/code/reidlog/mlr_market1501_hr_dsx2/x2sr'
#  save_dir: '/mnt/data/code/reidlog/mlr_market1501_hr_dsx2'

#  save_dir: '/mnt/data/code/reidlog/dist/mlr_market1501_split0'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 60
  batch_size: 128
  fixbase_epoch: 5
  open_layers: ['classifier']
  lr_scheduler: 'cosine'
  save_best_only: False

test:
  batch_size: 300
  dist_metric: 'cosine'
  normalize_feature: True
  eval_freq: 1
  rerank: False
  start_eval: 50
  evaluate: False
  save_distance: False
  compute_weight: False
#  visrank: True
